### ISSUE TITLE
I can't step up

### ISSUE THREAD

**Issue by jwjeong-bit** [kjy00302/pylooper#1]
import pygame
import pygame_gui

#initialize pygame
pygame.init()

#set title name
pygame.display.set_caption('LOOPER')
#set resulition 800*600
window_surface = pygame.display.set_mode((800, 600))

#make new image object
background = pygame.Surface((800, 600))
background.fill(pygame.Color('#000000'))

manager = pygame_gui.UIManager((800, 600))
#pygame_gui.elements.UIButton is designed to be pressed, do something and reset
#pygame.Rect : draw
play_button = pygame_gui.elements.UIButton(relative_rect=pygame.Rect((350, 275), (100, 50)),
                                             text='Play',
                                             manager=manager)
play_button = pygame_gui.elements.UIButton(relative_rect=pygame.Rect((350, 275), (100, 50)),
                                             text='Stop',
                                             manager=manager)

#how many times per second the screen is printed
clock = pygame.time.Clock()
is_running = True

#running until get event 'QUIT'
while is_running:
    time_delta = clock.tick(60)/1000.0
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            is_running = False

        manager.process_events(event)

    manager.update(time_delta)

    #Transfers the contents of one surface object onto another surface object
    window_surface.blit(background, (0, 0))
    manager.draw_ui(window_surface)

    #update part of the screen
    pygame.display.update()

**I'm modifying this code but i stucked also I can't find why use manager**

**Comment by kjy00302** [comment]
Your code has some problem
1. play_button variable is overwritten by second UIButton instance.
2. Both button has same size and position.
3. Code isn't indented.

Anyway, this is off-topic. Closing.
